// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'configuration_response_data_constants_dynamic_reward_ranks.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_ConfigurationResponseDataConstantsDynamicRewardRanks
    _$$_ConfigurationResponseDataConstantsDynamicRewardRanksFromJson(
            Map<String, dynamic> json) =>
        _$_ConfigurationResponseDataConstantsDynamicRewardRanks(
          rank1: json['1'] as int?,
          rank2: json['2'] as int?,
          rank3: json['3'] as int?,
          rank4: json['4'] as int?,
          rank5: json['5'] as int?,
          rank6: json['6'] as int?,
          rank7: json['7'] as int?,
          rank8: json['8'] as int?,
          rank9: json['9'] as int?,
          rank10: json['10'] as int?,
          rank11: json['11'] as int?,
          rank12: json['12'] as int?,
          rank13: json['13'] as int?,
          rank14: json['14'] as int?,
          rank15: json['15'] as int?,
          rank16: json['16'] as int?,
          rank17: json['17'] as int?,
          rank18: json['18'] as int?,
          rank19: json['19'] as int?,
          rank20: json['20'] as int?,
          rank21: json['21'] as int?,
          rank22: json['22'] as int?,
          rank23: json['23'] as int?,
          rank24: json['24'] as int?,
          rank25: json['25'] as int?,
          rank26: json['26'] as int?,
          rank27: json['27'] as int?,
          rank28: json['28'] as int?,
          rank29: json['29'] as int?,
          rank30: json['30'] as int?,
          rank31: json['31'] as int?,
          rank32: json['32'] as int?,
          rank33: json['33'] as int?,
          rank34: json['34'] as int?,
          rank35: json['35'] as int?,
          rank36: json['36'] as int?,
          rank37: json['37'] as int?,
          rank38: json['38'] as int?,
          rank39: json['39'] as int?,
          rank40: json['40'] as int?,
          rank41: json['41'] as int?,
          rank42: json['42'] as int?,
          rank43: json['43'] as int?,
          rank44: json['44'] as int?,
          rank45: json['45'] as int?,
          rank46: json['46'] as int?,
          rank47: json['47'] as int?,
          rank48: json['48'] as int?,
          rank49: json['49'] as int?,
          rank50: json['50'] as int?,
          rank51: json['51'] as int?,
          rank52: json['52'] as int?,
          rank53: json['53'] as int?,
        );

Map<String, dynamic>
    _$$_ConfigurationResponseDataConstantsDynamicRewardRanksToJson(
            _$_ConfigurationResponseDataConstantsDynamicRewardRanks instance) =>
        <String, dynamic>{
          '1': instance.rank1,
          '2': instance.rank2,
          '3': instance.rank3,
          '4': instance.rank4,
          '5': instance.rank5,
          '6': instance.rank6,
          '7': instance.rank7,
          '8': instance.rank8,
          '9': instance.rank9,
          '10': instance.rank10,
          '11': instance.rank11,
          '12': instance.rank12,
          '13': instance.rank13,
          '14': instance.rank14,
          '15': instance.rank15,
          '16': instance.rank16,
          '17': instance.rank17,
          '18': instance.rank18,
          '19': instance.rank19,
          '20': instance.rank20,
          '21': instance.rank21,
          '22': instance.rank22,
          '23': instance.rank23,
          '24': instance.rank24,
          '25': instance.rank25,
          '26': instance.rank26,
          '27': instance.rank27,
          '28': instance.rank28,
          '29': instance.rank29,
          '30': instance.rank30,
          '31': instance.rank31,
          '32': instance.rank32,
          '33': instance.rank33,
          '34': instance.rank34,
          '35': instance.rank35,
          '36': instance.rank36,
          '37': instance.rank37,
          '38': instance.rank38,
          '39': instance.rank39,
          '40': instance.rank40,
          '41': instance.rank41,
          '42': instance.rank42,
          '43': instance.rank43,
          '44': instance.rank44,
          '45': instance.rank45,
          '46': instance.rank46,
          '47': instance.rank47,
          '48': instance.rank48,
          '49': instance.rank49,
          '50': instance.rank50,
          '51': instance.rank51,
          '52': instance.rank52,
          '53': instance.rank53,
        };
