name: dart_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  dart_crypto:
    git:
      url: https://github.com/dutchpool/solar-dart-crypto
      ref: main

  # Network
  retrofit: ^3.0.1+1 # https://pub.dev/packages/retrofit
  dio: ^4.0.6 # https://pub.dev/packages/dio

  # Data/Sealed classes and json serialization
  freezed_annotation: ^2.0.3 # https://pub.dev/packages/freezed_annotation

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

  build_runner: # https://pub.dev/packages/build_runner

  # Data/Sealed classes and json serialization
  freezed: ^2.0.3+1 # https://pub.dev/packages/freezed
  json_serializable: ^6.1.5 # https://pub.dev/packages/json_serializable
  json_annotation: ^4.5.0

  # Retrofit
  retrofit_generator: 4.0.1 # https://pub.dev/packages/retrofit
